select * from customer limit 20

-- 1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount)
from customer
group by gender


-- 2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


-- 3. Which are the top 5 products with the highest average review rating?
select item_purchased as "Item Purchased", ROUND(AVG(review_rating::numeric), 2) as "Average Product Rating"
from customer
group by item_purchased
order by AVG(review_rating) desc
limit 5


-- 4. Compare average purchase amounts between shipping types
select shipping_type as "Shipping Type", ROUND(AVG(purchase_amount), 2) as "Average Purchase Amount"
from customer
group by shipping_type
ord
er by AVG(purchase_amount) desc

-- 5. Do subscribed customers spend more?
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount), 2) as average_spend,
ROUND(SUM(purchase_amount), 2) as total_spend
from customer
group by subscription_status
order by average_spend, total_spend desc


-- 6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5


-- 7. Segment customers into New, Returning & Loyal based on number of previous purchases 
with customer_type as (
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment


-- 8. What are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by COUNT(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3


-- 9. Are repeat buyers (> 5 previous purchases) likely to subscribe?
select subscription_status as "Subscribed?", 
COUNT(customer_id) as "Repeat Buyers"
from customer
where previous_purchases > 5
group by subscription_status


-- 10. How much revenue does each age group contribute?
select age_group,
CONCAT('£', SUM(purchase_amount)) as total_revenue
from customer
group by age_group
order by total_revenue desc